version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=xaldigital_local
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_PASSWORD=debug
      - POSTGRES_USER=debug
    ports:
      - "9090:5432"